// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOK2nZ0OuBfxyWbMhawHgJp1uBbVH-d3o',
    appId: '1:476459834022:android:fcd0cb9270942501987267',
    messagingSenderId: '476459834022',
    projectId: 'threeten-labs-template',
    storageBucket: 'threeten-labs-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAusyIkeXWn_0mORQOCE_MJhOktRr3FCCQ',
    appId: '1:476459834022:ios:713bd6b7945c5e7b987267',
    messagingSenderId: '476459834022',
    projectId: 'threeten-labs-template',
    storageBucket: 'threeten-labs-template.appspot.com',
    androidClientId: '476459834022-1vbbjgi8ge41su31r9et1tbqp4mc6cdj.apps.googleusercontent.com',
    iosClientId: '476459834022-7uov3abjhs46oqnk7a4tgd8bk9ju1a7g.apps.googleusercontent.com',
    iosBundleId: 'com.threetenlabs.template',
  );
}
