# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  slack_url = 'https://hooks.slack.com/services/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'

  desc "Submit a new Beta Build to Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'completed',
      timeout: 300,
    )
    slack(
      message: 'New Android build uploaded to Play Store',
      slack_url: slack_url
    )
  end
end